services:
  location.curl_client:
    class: LocationBundle\Component\CurlClient
    arguments:
      - @logger

  location.service_client:
    class: LocationBundle\Service\ServiceClient
    arguments:
      - @location.curl_client
      - %location_service_host% # example: http://location.local:4002
